import { useCallback, useMemo, useState } from 'react'
import { api, type HardwareHistoryMetric, type HardwareHistoryPoint, type HardwareHistoryRange, type HardwareSummary } from '../services/api'
import { useApiResource } from '../services/use-api-resource'
import { useLanguage } from '../i18n/LanguageContext'
import './Hardware.css'

const metrics: Array<{ id: HardwareHistoryMetric; zh: string; en: string; unit: string }> = [
  { id: 'gpuUtilizationPercent', zh: 'GPU 利用率', en: 'GPU utilization', unit: '%' },
  { id: 'cpuPercent', zh: 'CPU 利用率', en: 'CPU utilization', unit: '%' },
  { id: 'memoryUsedPercent', zh: '内存已用', en: 'Memory used', unit: '%' },
  { id: 'rootUsedPercent', zh: '根分区已用', en: 'Root disk used', unit: '%' },
]
const ranges: Array<{ id: HardwareHistoryRange; zh: string; en: string }> = [
  { id: '15m', zh: '15 分钟', en: '15 minutes' }, { id: '1h', zh: '1 小时', en: '1 hour' }, { id: '6h', zh: '6 小时', en: '6 hours' }, { id: '24h', zh: '24 小时', en: '24 hours' }, { id: '7d', zh: '7 天', en: '7 days' },
]
function number(value: number | null | undefined, digits = 0) { return value === null || value === undefined || !Number.isFinite(value) ? '—' : value.toFixed(digits) }
function bytes(value: number | null | undefined) { return value === null || value === undefined || !Number.isFinite(value) ? '—' : `${(value / 1024 ** 3).toFixed(1)} GiB` }
function elapsed(value: number | null | undefined) { if (value === null || value === undefined || value < 0) return '—'; const days = Math.floor(value / 86_400); const hours = Math.floor((value % 86_400) / 3_600); const minutes = Math.floor((value % 3_600) / 60); return days > 0 ? `${days}d ${hours}h` : `${hours}h ${minutes}m` }
function stateLabel(summary: HardwareSummary | undefined, english: boolean) { if (!summary || summary.status === 'unavailable') return english ? 'Unavailable' : '不可用'; if (summary.status === 'not-configured') return english ? 'Not configured' : '尚未配置'; if (summary.freshness.state !== 'fresh') return english ? 'Data may be stale' : '数据可能过期'; if (summary.freshness.cached) return english ? 'Cached read-only data' : '只读缓存数据'; return english ? 'Live read-only data' : '实时只读数据' }
function trendPath(points: HardwareHistoryPoint[], width = 620, height = 150) { const usable = points.filter((point) => point.state === 'fresh' && point.value !== null).map((point) => point.value as number); if (usable.length < 2) return null; const min = Math.min(...usable); const max = Math.max(...usable); const extent = max - min || 1; let index = 0; return points.map((point) => { if (point.state !== 'fresh' || point.value === null) return ''; const x = (index / Math.max(usable.length - 1, 1)) * width; const y = height - (((point.value - min) / extent) * height); index += 1; return `${index === 1 ? 'M' : 'L'} ${x.toFixed(1)} ${y.toFixed(1)}` }).filter(Boolean).join(' ') }

export default function Hardware() {
  const { locale } = useLanguage(); const english = locale === 'en-US'; const [metric, setMetric] = useState<HardwareHistoryMetric>('gpuUtilizationPercent'); const [range, setRange] = useState<HardwareHistoryRange>('1h')
  const loadSummary = useCallback(() => api.getHardwareSummaryState(), []); const loadHistory = useCallback(() => api.getHardwareHistoryState(metric, range), [metric, range])
  const summary = useApiResource(loadSummary, 5_000); const history = useApiResource(loadHistory, 15_000); const data = summary.data; const selectedMetric = metrics.find((item) => item.id === metric) ?? metrics[0]; const path = useMemo(() => trendPath(history.data ?? []), [history.data]); const statusClass = !data || data.status === 'unavailable' ? 'is-unavailable' : data.status === 'not-configured' ? 'is-unconfigured' : data.freshness.state !== 'fresh' ? 'is-stale' : 'is-ready'; const canShowDetails = data?.status !== 'unavailable' && data?.status !== 'not-configured'
  return <div className="hardware-page">
    <header className="hardware-header"><div><p className="eyebrow">{english ? 'READ-ONLY HARDWARE' : '只读硬件监控'}</p><h2>{english ? 'DGX hardware status' : 'DGX 硬件状态'}</h2><p>{english ? 'Uses only fixed system telemetry. It does not contact model ports or start, stop, or reconfigure services.' : '只读取固定系统遥测数据；不会访问模型端口，也不会启动、停止或修改任何服务。'}</p></div><button className="btn btn-secondary" onClick={summary.refresh} disabled={summary.isLoading}>{english ? 'Refresh' : '刷新状态'}</button></header>
    <section className={`hardware-state ${statusClass}`} aria-live="polite"><div><span className="hardware-state-dot" /><strong>{stateLabel(data, english)}</strong></div><p>{data?.collectedAt ? `${english ? 'Collected' : '采集时间'}：${new Date(data.collectedAt).toLocaleString(english ? 'en-US' : 'zh-CN')}` : (english ? 'No hardware snapshot is available.' : '尚未获得硬件快照。')}</p></section>
    {!canShowDetails ? <section className="hardware-empty"><h3>{english ? 'Hardware data is not available' : '硬件数据暂不可用'}</h3><p>{data?.status === 'not-configured' ? (english ? 'Complete a verified DGX connection, then enable the read-only session to collect fixed system telemetry.' : '请先完成已验证的 DGX 连接，并启用只读会话后再采集固定系统遥测。') : (english ? 'The latest read-only collection could not be completed. No value has been replaced with a simulated number.' : '最近一次只读采集未完成；页面不会以模拟数值替代真实数据。')}</p></section> : <>
      <section className="hardware-grid" aria-label={english ? 'Hardware summary' : '硬件概要'}>
        <article><span>{english ? 'GPU utilization' : 'GPU 利用率'}</span><strong>{number(data?.gpu?.utilizationPercent)}<small>%</small></strong><p>{data?.gpu?.supported === false ? (english ? 'Unsupported by this DGX' : '当前 DGX 不支持此项') : `${english ? 'Temperature' : '温度'} ${number(data?.gpu?.temperatureC)} °C`}</p></article>
        <article><span>{english ? 'GPU power' : 'GPU 功耗'}</span><strong>{number(data?.gpu?.powerWatts, 1)}<small> W</small></strong><p>{english ? 'Unified memory' : '统一内存'} {bytes(data?.gpu?.memoryUsedBytes)} / {bytes(data?.gpu?.memoryTotalBytes)}</p></article>
        <article><span>{english ? 'CPU utilization' : 'CPU 利用率'}</span><strong>{number(data?.system?.cpuPercent)}<small>%</small></strong><p>{english ? 'Load' : '负载'} {number(data?.system?.load1, 2)} / {number(data?.system?.load5, 2)} / {number(data?.system?.load15, 2)}</p></article>
        <article><span>{english ? 'System memory' : '系统内存'}</span><strong>{number(data?.memory?.usedPercent)}<small>%</small></strong><p>{bytes(data?.memory?.usedBytes)} / {bytes(data?.memory?.totalBytes)}</p></article>
        <article><span>{english ? 'Root disk' : '根分区磁盘'}</span><strong>{number(data?.storage?.rootUsedPercent)}<small>%</small></strong><p>{bytes(data?.storage?.rootUsedBytes)} / {bytes(data?.storage?.rootTotalBytes)}</p></article>
        <article><span>{english ? 'System uptime' : '系统运行时间'}</span><strong className="hardware-text-value">{elapsed(data?.system?.uptimeSeconds)}</strong><p>{english ? 'Swap used' : '交换分区已用'} {bytes(data?.memory?.swapUsedBytes)} / {bytes(data?.memory?.swapTotalBytes)}</p></article>
      </section>
      <section className="hardware-section"><div className="hardware-section-heading"><div><p className="eyebrow">{english ? 'LOCAL HISTORY' : '本地历史'}</p><h3>{english ? 'Hardware trend' : '硬件趋势'}</h3></div><div className="hardware-controls"><select value={metric} onChange={(event) => setMetric(event.target.value as HardwareHistoryMetric)} aria-label={english ? 'Metric' : '指标'}>{metrics.map((item) => <option value={item.id} key={item.id}>{english ? item.en : item.zh}</option>)}</select><select value={range} onChange={(event) => setRange(event.target.value as HardwareHistoryRange)} aria-label={english ? 'Range' : '范围'}>{ranges.map((item) => <option value={item.id} key={item.id}>{english ? item.en : item.zh}</option>)}</select></div></div>{history.stale ? <p className="hardware-trend-note">{english ? 'The latest history read failed; retaining the last verified local history.' : '最近一次历史读取失败，当前保留上次已验证的本地历史。'}</p> : null}{path ? <div className="hardware-trend"><svg viewBox="0 0 620 180" role="img" aria-label={english ? `${selectedMetric.en} trend` : `${selectedMetric.zh}趋势`}><line x1="0" y1="35" x2="620" y2="35" /><line x1="0" y1="90" x2="620" y2="90" /><line x1="0" y1="145" x2="620" y2="145" /><path d={path} /></svg><p>{english ? `${selectedMetric.en} (${selectedMetric.unit}) · only fresh observations are drawn` : `${selectedMetric.zh}（${selectedMetric.unit}）· 仅绘制新鲜采样点`}</p></div> : <div className="hardware-trend-empty"><strong>{english ? 'Not enough verified observations yet' : '暂时没有足够的已验证采样点'}</strong><p>{english ? 'History begins after this version collects read-only snapshots. Unavailable periods remain gaps and are not drawn as zero.' : '历史从本版本开始采集只读快照；不可用时段会保留为空白，不会绘制为 0。'}</p></div>}</section>
      <section className="hardware-section"><div className="hardware-section-heading"><div><p className="eyebrow">{english ? 'SYSTEM COMPONENTS' : '系统组件'}</p><h3>{english ? 'Fixed component status' : '固定组件状态'}</h3></div><button className="btn btn-secondary" onClick={summary.refresh} disabled={summary.isLoading}>{english ? 'Refresh' : '刷新'}</button></div><div className="hardware-components">{(data?.components ?? []).map((component) => <div key={component.id} className={`component-${component.state}`}><span aria-hidden="true" /><strong>{component.id}</strong><em>{component.state === 'active' ? (english ? 'Active' : '运行中') : component.state === 'inactive' ? (english ? 'Inactive' : '未运行') : (english ? 'Unknown' : '未知')}</em></div>)}</div></section>
    </>}
  </div>
}
